using SolastaUnfinishedBusiness.Interfaces;

namespace SolastaUnfinishedBusiness.Definitions;

internal class FeatureDefinitionAttackReplaceWithCantrip : FeatureDefinition, IAttackReplaceWithCantrip;
