//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolastaCommunityExpansion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolastaCommunityExpansion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AcidClaws {
            get {
                object obj = ResourceManager.GetObject("AcidClaws", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AirBlast {
            get {
                object obj = ResourceManager.GetObject("AirBlast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bolgrif {
            get {
                object obj = ResourceManager.GetObject("Bolgrif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BurstOfRadiance {
            get {
                object obj = ResourceManager.GetObject("BurstOfRadiance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ContentPack {
            get {
                object obj = ResourceManager.GetObject("ContentPack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Destination {
            get {
                object obj = ResourceManager.GetObject("Destination", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EarthTremor {
            get {
                object obj = ResourceManager.GetObject("EarthTremor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EldritchBlast {
            get {
                object obj = ResourceManager.GetObject("EldritchBlast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EldritchBlastGrasp {
            get {
                object obj = ResourceManager.GetObject("EldritchBlastGrasp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EldritchBlastRepell {
            get {
                object obj = ResourceManager.GetObject("EldritchBlastRepell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EldritchInvocation {
            get {
                object obj = ResourceManager.GetObject("EldritchInvocation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ElementalForm {
            get {
                object obj = ResourceManager.GetObject("ElementalForm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ElementalFormEnhanced {
            get {
                object obj = ResourceManager.GetObject("ElementalFormEnhanced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ElementalFormIcon {
            get {
                object obj = ResourceManager.GetObject("ElementalFormIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ElementalFormIconEnhanced {
            get {
                object obj = ResourceManager.GetObject("ElementalFormIconEnhanced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Entry {
            get {
                object obj = ResourceManager.GetObject("Entry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fire {
            get {
                object obj = ResourceManager.GetObject("Fire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlurryOfArrows {
            get {
                object obj = ResourceManager.GetObject("FlurryOfArrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gnome {
            get {
                object obj = ResourceManager.GetObject("Gnome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Halberd {
            get {
                object obj = ResourceManager.GetObject("Halberd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Halberd_1 {
            get {
                object obj = ResourceManager.GetObject("Halberd_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Halberd_2 {
            get {
                object obj = ResourceManager.GetObject("Halberd_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HalberdLightning {
            get {
                object obj = ResourceManager.GetObject("HalberdLightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HalberdPrimed {
            get {
                object obj = ResourceManager.GetObject("HalberdPrimed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HandXbow {
            get {
                object obj = ResourceManager.GetObject("HandXbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HandXbow_1 {
            get {
                object obj = ResourceManager.GetObject("HandXbow_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HandXbow_2 {
            get {
                object obj = ResourceManager.GetObject("HandXbow_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HandXbowAcid {
            get {
                object obj = ResourceManager.GetObject("HandXbowAcid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HandXbowPrimed {
            get {
                object obj = ResourceManager.GetObject("HandXbowPrimed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HellishRebuke {
            get {
                object obj = ResourceManager.GetObject("HellishRebuke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LongMace {
            get {
                object obj = ResourceManager.GetObject("LongMace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LongMace_1 {
            get {
                object obj = ResourceManager.GetObject("LongMace_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LongMace_2 {
            get {
                object obj = ResourceManager.GetObject("LongMace_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LongMacePrimed {
            get {
                object obj = ResourceManager.GetObject("LongMacePrimed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LongMaceThunder {
            get {
                object obj = ResourceManager.GetObject("LongMaceThunder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Alle zum Shop hinzufügen
        ///ModUi/&amp;AddBleedingToLesserRestoration	Fügen Sie den Zustand &lt;color=orange&gt;Bluten&lt;/color&gt; zu den Zuständen hinzu, die durch &lt;color=orange&gt;Größere und Geringere Wiederherstellung&lt;/color&gt; entfernt wurden
        ///ModUi/&amp;AddHelpActionToAllRaces	Füge allen Rennen die Aktion &lt;color=orange&gt;Hilfe&lt;/color&gt; hinzu
        ///ModUi/&amp;AddPickpocketableLoot	Taschendiebstahl-Beute hinzufügen &lt;i&gt;&lt;color=yellow&gt;[empfohlen, wenn &lt;color=orange&gt;Taschendiebstahl&lt;/color&gt;-Talent aktiviert ist]&lt;/color&gt;&lt;/i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_de {
            get {
                return ResourceManager.GetString("Modui-de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Add all to store
        ///ModUi/&amp;AddBleedingToLesserRestoration	Add the &lt;color=orange&gt;Bleeding&lt;/color&gt; condition to the conditions removed by &lt;color=orange&gt;Greater and Lesser Restoration&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Add the &lt;color=orange&gt;Help&lt;/color&gt; action to all races
        ///ModUi/&amp;AddPickpocketableLoot	Add pickpocketable loot &lt;i&gt;&lt;color=yellow&gt;[suggested if &lt;color=orange&gt;Pickpocket&lt;/color&gt; feat is enabled]&lt;/color&gt;&lt;/i&gt;
        ///ModUi/&amp;AddToStore	Add to store
        ///ModUi/&amp;Advanced	&lt;color=yellow&gt;Advance [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_en {
            get {
                return ResourceManager.GetString("Modui-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Ajouter tout au magasin
        ///ModUi/&amp;AddBleedingToLesserRestoration	Ajoutez la condition &lt;color=orange&gt;Saignement&lt;/color&gt; aux conditions supprimées par &lt;color=orange&gt;Grande et Petite Restauration&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Ajouter l&apos;action &lt;color=orange&gt;Aide&lt;/color&gt; à toutes les courses
        ///ModUi/&amp;AddPickpocketableLoot	Ajouter un butin pickpocketable &lt;i&gt;&lt;color=yellow&gt;[suggéré si la fonctionnalité &lt;color=orange&gt;Pickpocket&lt;/color&gt; est activée]&lt;/color&gt;&lt;/i&gt;
        ///ModUi/&amp;AddToStore	Ajouter a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_fr {
            get {
                return ResourceManager.GetString("Modui-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Adicionar tudo à loja
        ///ModUi/&amp;AddBleedingToLesserRestoration	Adicione a condição &lt;color=orange&gt;Sangramento&lt;/color&gt; às condições removidas pela &lt;color=orange&gt;Restauração Maior e Menor&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Adicione a ação &lt;color=orange&gt;Ajuda&lt;/color&gt; a todas as corridas
        ///ModUi/&amp;AddPickpocketableLoot	Adicionar espólio de carteirista &lt;i&gt;&lt;color=yellow&gt;[sugerido se o recurso &lt;color=orange&gt;Pocket&lt;/color&gt; estiver ativado]&lt;/color&gt;&lt;/i&gt;
        ///ModUi/&amp;AddToStore	Adicionar à loja
        ///ModUi/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_pt_BR {
            get {
                return ResourceManager.GetString("Modui-pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Добавить все в магазин
        ///ModUi/&amp;AddBleedingToLesserRestoration	Добавьте состояние &lt;color=orange&gt;Кровотечение&lt;/color&gt; к состояниям, удаленным с помощью &lt;color=orange&gt;Большого и малого восстановления&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Добавьте действие &lt;color=orange&gt;Помощь&lt;/color&gt; ко всем гонкам.
        ///ModUi/&amp;AddPickpocketableLoot	Добавить добычу для карманных краж &lt;i&gt;&lt;color=yellow&gt;[предлагается, если умение &lt;color=orange&gt;Карманные кражи&lt;/color&gt; включено]&lt;/color&gt;&lt;/i&gt;
        ///ModUi/&amp;AddToStore	Доб [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_ru {
            get {
                return ResourceManager.GetString("Modui-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	全部加入商店
        ///ModUi/&amp;AddBleedingToLesserRestoration	添加&lt;color=orange&gt;流血&lt;/color&gt;状态至&lt;color=orange&gt;次级/高等复原术&lt;/color&gt;的移除效果范围
        ///ModUi/&amp;AddHelpActionToAllRaces	添加&lt;color=orange&gt;协助&lt;/color&gt;至全部种族
        ///ModUi/&amp;AddPickpocketableLoot	添加可扒窃的战利品 &lt;i&gt;&lt;color=yellow&gt;[建议在&lt;color=orange&gt;扒窃&lt;/color&gt;专长被启用时启用]&lt;/color&gt;&lt;/i&gt;
        ///ModUi/&amp;AddToStore	加入商店
        ///ModUi/&amp;Advanced	&lt;color=yellow&gt;进阶选项：&lt;/color&gt;
        ///ModUi/&amp;AdvancedHelp	. &lt;b&gt;&lt;color=#C04040E0&gt;注意：&lt;/color&gt;&lt;/b&gt; 此项设置将要求玩家安装此Mod
        ///ModUi/&amp;Adventure	&lt;color=yellow&gt;冒险：&lt;/color&gt;
        ///ModUi/&amp;AllItemInDm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_zh_CN {
            get {
                return ResourceManager.GetString("Modui-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Monk {
            get {
                object obj = ResourceManager.GetObject("Monk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkEmptyBody {
            get {
                object obj = ResourceManager.GetObject("MonkEmptyBody", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkFlurryOfBlows {
            get {
                object obj = ResourceManager.GetObject("MonkFlurryOfBlows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkKiIcon {
            get {
                object obj = ResourceManager.GetObject("MonkKiIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkPatientDefense {
            get {
                object obj = ResourceManager.GetObject("MonkPatientDefense", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkPictogram {
            get {
                object obj = ResourceManager.GetObject("MonkPictogram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkSlowFall {
            get {
                object obj = ResourceManager.GetObject("MonkSlowFall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkStepOfTheWind {
            get {
                object obj = ResourceManager.GetObject("MonkStepOfTheWind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkStillnessOfMind {
            get {
                object obj = ResourceManager.GetObject("MonkStillnessOfMind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MonkStunningStrike {
            get {
                object obj = ResourceManager.GetObject("MonkStunningStrike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Umgekehrte Schwerkraft
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Umgekehrte Schwerkraft
        ///Condition/&amp;DH_TimeStop_Spell_Description	Eingefroren durch Zeitstopp
        ///Condition/&amp;DH_TimeStop_Spell_Title	Eingefroren durch Zeitstopp
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Gewitter
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Gewitter
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Beliebiger Feuerball
        ///Feature/&amp;DH_AtWill_Fireball_Power_Titl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_de {
            get {
                return ResourceManager.GetString("Monsters-de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Reverse Gravity
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Reverse Gravity
        ///Condition/&amp;DH_TimeStop_Spell_Description	Frozen by Time Stop
        ///Condition/&amp;DH_TimeStop_Spell_Title	Frozen by Time Stop
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Lightning Storm
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Lightning Storm
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	At-will Fireball
        ///Feature/&amp;DH_AtWill_Fireball_Power_Title	Fireball
        ///Feature/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_en {
            get {
                return ResourceManager.GetString("Monsters-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Gravité inversée
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Gravité inversée
        ///Condition/&amp;DH_TimeStop_Spell_Description	Gelé par l&apos;arrêt du temps
        ///Condition/&amp;DH_TimeStop_Spell_Title	Gelé par l&apos;arrêt du temps
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Orage
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Orage
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Boule de feu à volonté
        ///Feature/&amp;DH_AtWill_Fireball_Power_Title	Boule de feu
        ///Feat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_fr {
            get {
                return ResourceManager.GetString("Monsters-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Gravidade reversa
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Gravidade reversa
        ///Condition/&amp;DH_TimeStop_Spell_Description	Congelado por Parada de Tempo
        ///Condition/&amp;DH_TimeStop_Spell_Title	Congelado por Parada de Tempo
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Tempestade Relâmpago
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Tempestade Relâmpago
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Bola de fogo à vontade
        ///Feature/&amp;DH_AtWill [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_pt_BR {
            get {
                return ResourceManager.GetString("Monsters-pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Обратная гравитация
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Обратная гравитация
        ///Condition/&amp;DH_TimeStop_Spell_Description	Застыло на остановке времени
        ///Condition/&amp;DH_TimeStop_Spell_Title	Застыло на остановке времени
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Грозовой шторм
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Грозовой шторм
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Неограниченный огненный шар
        ///Feature/&amp;DH_AtWill_Fire [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_ru {
            get {
                return ResourceManager.GetString("Monsters-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster/&amp;DH_Custom_AirTitan_Description	当被召唤时，这些年长的元素聚现为具有灭世能力的生物，它们的存在就会带来毁灭
        ///Monster/&amp;DH_Custom_AirTitan_Title	&lt;color=#ff0000ff&gt;原初空气泰坦&lt;/color&gt;
        ///Monster/&amp;DH_Custom_AncientBlackDragon_Description	作为色彩龙中最暴躁卑劣的种类，黑龙会将倒毙者的残骸连同其财宝一同收集起来。黑龙们厌恶眼见弱者的兴盛，并乐见类人生物王国崩溃。恶臭的沼泽，以及覆亡王国曾经耸立的废墟瓦砾会是他们理想的家园
        ///Monster/&amp;DH_Custom_AncientBlackDragon_Title	&lt;color=#ff0000ff&gt;远古黑龙&lt;/color&gt;
        ///Monster/&amp;DH_Custom_AncientBlueDragon_Description	自负且极具领土意识的蓝龙翱翔于沙漠的天空之上，时常捕食商队并在沙漠边际的旷野狩猎畜群和定居者。这种龙也会出现在干燥的草原，灼热的荒漠以及多岩的海岸，他们会守卫自己的领地而对抗所有潜在的对手，特别是 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_zh_CN {
            get {
                return ResourceManager.GetString("Monsters-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DwarfFemale	Dearma
        ///DwarfFemale	Jenrin
        ///DwarfFemale	Nisleen
        ///DwarfFemale	Misnan
        ///DwarfFemale	Jenndora
        ///DwarfFemale	Renmera
        ///DwarfFemale	Nasnyl
        ///DwarfFemale	Brallesyl
        ///DwarfFemale	Torthiel
        ///DwarfFemale	Myrnera
        ///DwarfFemale	Bretri
        ///DwarfFemale	Abagtha
        ///DwarfFemale	Bera
        ///DwarfFemale	Birsha
        ///DwarfFemale	Clauda
        ///DwarfFemale	Dabareh
        ///DwarfFemale	Demelza
        ///DwarfFemale	Dodai
        ///DwarfFemale	Dura
        ///DwarfFemale	Gath
        ///DwarfFemale	Hadar
        ///DwarfFemale	Hagar
        ///DwarfFemale	Halah
        ///DwarfFemale	Hanan
        ///DwarfFemale	Iddo
        ///DwarfFemale	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Names_en {
            get {
                return ResourceManager.GetString("Names-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pike {
            get {
                object obj = ResourceManager.GetObject("Pike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pike_1 {
            get {
                object obj = ResourceManager.GetObject("Pike_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pike_2 {
            get {
                object obj = ResourceManager.GetObject("Pike_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PikePrimed {
            get {
                object obj = ResourceManager.GetObject("PikePrimed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PikePsychic {
            get {
                object obj = ResourceManager.GetObject("PikePsychic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PowerAttackConcentrationIcon {
            get {
                object obj = ResourceManager.GetObject("PowerAttackConcentrationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PowerAttackIcon {
            get {
                object obj = ResourceManager.GetObject("PowerAttackIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ResonatingStrike {
            get {
                object obj = ResourceManager.GetObject("ResonatingStrike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SharpShooterConcentrationIcon {
            get {
                object obj = ResourceManager.GetObject("SharpShooterConcentrationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SharpShooterIcon {
            get {
                object obj = ResourceManager.GetObject("SharpShooterIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SunlightBlade {
            get {
                object obj = ResourceManager.GetObject("SunlightBlade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Teleport {
            get {
                object obj = ResourceManager.GetObject("Teleport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Kann keine Zauber wirken.
        ///ActionAffinity/&amp;DHFeeblemindSpellTitle	Schwache Zauberei
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC ist auf 16 eingestellt.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Rindenleder
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Charismawert ist gleich 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Schwaches Charisma
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Intelligenzwer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_de {
            get {
                return ResourceManager.GetString("Translations-de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Unable to cast spells.
        ///ActionAffinity/&amp;DHFeeblemindSpellTitle	Feeble spellcasting
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC is set to 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Barkskin
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Charisma score equals 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Feeble Charisma
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Intelligence score equals 1.
        ///Att [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_en {
            get {
                return ResourceManager.GetString("Translations-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Impossible de lancer des sorts.
        ///ActionAffinity/&amp;DHFeeblemindSpellTitle	Lancement de sorts faible
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	CA est réglé sur 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Écorce
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Le score de Charisme est égal à 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Charisme faible
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Le sco [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_fr {
            get {
                return ResourceManager.GetString("Translations-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Incapaz de lançar feitiços.
        ///ActionAffinity/&amp;DHFeeblemindSpellTitle	Feitiço fraco
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC está definido para 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Barkskin
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	A pontuação de Carisma é igual a 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Carisma fraco
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	A pontuação de i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_pt_BR {
            get {
                return ResourceManager.GetString("Translations-pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Невозможно читать заклинания.
        ///ActionAffinity/&amp;DHFeeblemindSpellTitle	Слабое колдовство
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC настроен на 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Дубовая кожа
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Показатель харизмы равен 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Слабая харизма
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Показатель интеллект [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_ru {
            get {
                return ResourceManager.GetString("Translations-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	无法施法
        ///ActionAffinity/&amp;DHFeeblemindSpellTitle	施法能力衰减
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC设为16
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	树肤术
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	魅力值为1
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	魅力衰减
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	智力值为1
        ///AttributeModifier/&amp;DHFeeblemindIntSpellTitle	智力衰减
        ///BlueprintCategory/&amp;FlatRoomsTitle	平房
        ///Caption/&amp;Gadg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_zh_CN {
            get {
                return ResourceManager.GetString("Translations-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Warlock {
            get {
                object obj = ResourceManager.GetObject("Warlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WarlockChainSummon {
            get {
                object obj = ResourceManager.GetObject("WarlockChainSummon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WinterBreath {
            get {
                object obj = ResourceManager.GetObject("WinterBreath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZenArrow {
            get {
                object obj = ResourceManager.GetObject("ZenArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
