//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolastaCommunityExpansion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolastaCommunityExpansion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AcidClaws {
            get {
                object obj = ResourceManager.GetObject("AcidClaws", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AirBlast {
            get {
                object obj = ResourceManager.GetObject("AirBlast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Bolgrif {
            get {
                object obj = ResourceManager.GetObject("Bolgrif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BurstOfRadiance {
            get {
                object obj = ResourceManager.GetObject("BurstOfRadiance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ContentPack {
            get {
                object obj = ResourceManager.GetObject("ContentPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Darkelf {
            get {
                object obj = ResourceManager.GetObject("Darkelf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DeadeyeConcentrationIcon {
            get {
                object obj = ResourceManager.GetObject("DeadeyeConcentrationIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DeadeyeIcon {
            get {
                object obj = ResourceManager.GetObject("DeadeyeIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EarthTremor {
            get {
                object obj = ResourceManager.GetObject("EarthTremor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchBlast {
            get {
                object obj = ResourceManager.GetObject("EldritchBlast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchBlastGrasp {
            get {
                object obj = ResourceManager.GetObject("EldritchBlastGrasp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchBlastRepell {
            get {
                object obj = ResourceManager.GetObject("EldritchBlastRepell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchInvocation {
            get {
                object obj = ResourceManager.GetObject("EldritchInvocation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalForm {
            get {
                object obj = ResourceManager.GetObject("ElementalForm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalFormEnhanced {
            get {
                object obj = ResourceManager.GetObject("ElementalFormEnhanced", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalFormIcon {
            get {
                object obj = ResourceManager.GetObject("ElementalFormIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalFormIconEnhanced {
            get {
                object obj = ResourceManager.GetObject("ElementalFormIconEnhanced", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Entry {
            get {
                object obj = ResourceManager.GetObject("Entry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fire {
            get {
                object obj = ResourceManager.GetObject("Fire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FlurryOfArrows {
            get {
                object obj = ResourceManager.GetObject("FlurryOfArrows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gnome {
            get {
                object obj = ResourceManager.GetObject("Gnome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Halberd {
            get {
                object obj = ResourceManager.GetObject("Halberd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Halberd_1 {
            get {
                object obj = ResourceManager.GetObject("Halberd_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Halberd_2 {
            get {
                object obj = ResourceManager.GetObject("Halberd_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HalberdLightning {
            get {
                object obj = ResourceManager.GetObject("HalberdLightning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HalberdPrimed {
            get {
                object obj = ResourceManager.GetObject("HalberdPrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbow {
            get {
                object obj = ResourceManager.GetObject("HandXbow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbow_1 {
            get {
                object obj = ResourceManager.GetObject("HandXbow_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbow_2 {
            get {
                object obj = ResourceManager.GetObject("HandXbow_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbowAcid {
            get {
                object obj = ResourceManager.GetObject("HandXbowAcid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbowPrimed {
            get {
                object obj = ResourceManager.GetObject("HandXbowPrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HellishRebuke {
            get {
                object obj = ResourceManager.GetObject("HellishRebuke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMace {
            get {
                object obj = ResourceManager.GetObject("LongMace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMace_1 {
            get {
                object obj = ResourceManager.GetObject("LongMace_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMace_2 {
            get {
                object obj = ResourceManager.GetObject("LongMace_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMacePrimed {
            get {
                object obj = ResourceManager.GetObject("LongMacePrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMaceThunder {
            get {
                object obj = ResourceManager.GetObject("LongMaceThunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Monk {
            get {
                object obj = ResourceManager.GetObject("Monk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkEmptyBody {
            get {
                object obj = ResourceManager.GetObject("MonkEmptyBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkFlurryOfBlows {
            get {
                object obj = ResourceManager.GetObject("MonkFlurryOfBlows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkKiIcon {
            get {
                object obj = ResourceManager.GetObject("MonkKiIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkPatientDefense {
            get {
                object obj = ResourceManager.GetObject("MonkPatientDefense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkPictogram {
            get {
                object obj = ResourceManager.GetObject("MonkPictogram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkSlowFall {
            get {
                object obj = ResourceManager.GetObject("MonkSlowFall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkStepOfTheWind {
            get {
                object obj = ResourceManager.GetObject("MonkStepOfTheWind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkStillnessOfMind {
            get {
                object obj = ResourceManager.GetObject("MonkStillnessOfMind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkStunningStrike {
            get {
                object obj = ResourceManager.GetObject("MonkStunningStrike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DwarfFemale	Abagtha
        ///DwarfFemale	Bera
        ///DwarfFemale	Birsha
        ///DwarfFemale	Brallesyl
        ///DwarfFemale	Bretri
        ///DwarfFemale	Bronnura
        ///DwarfFemale	Clauda
        ///DwarfFemale	Dabareh
        ///DwarfFemale	Dearma
        ///DwarfFemale	Demelza
        ///DwarfFemale	Dodai
        ///DwarfFemale	Dura
        ///DwarfFemale	Gath
        ///DwarfFemale	Hadar
        ///DwarfFemale	Hagar
        ///DwarfFemale	Halah
        ///DwarfFemale	Hanan
        ///DwarfFemale	Iddo
        ///DwarfFemale	Jenndora
        ///DwarfFemale	Jenrin
        ///DwarfFemale	Juttah
        ///DwarfFemale	Melea
        ///DwarfFemale	Meribah
        ///DwarfFemale	Misnan
        ///DwarfFemale	Myrnera
        ///DwarfFemale	Na [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Pike {
            get {
                object obj = ResourceManager.GetObject("Pike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Pike_1 {
            get {
                object obj = ResourceManager.GetObject("Pike_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Pike_2 {
            get {
                object obj = ResourceManager.GetObject("Pike_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PikePrimed {
            get {
                object obj = ResourceManager.GetObject("PikePrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PikePsychic {
            get {
                object obj = ResourceManager.GetObject("PikePsychic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PowerAttackConcentrationIcon {
            get {
                object obj = ResourceManager.GetObject("PowerAttackConcentrationIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PowerAttackIcon {
            get {
                object obj = ResourceManager.GetObject("PowerAttackIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ResonatingStrike {
            get {
                object obj = ResourceManager.GetObject("ResonatingStrike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SunlightBlade {
            get {
                object obj = ResourceManager.GetObject("SunlightBlade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Teleport {
            get {
                object obj = ResourceManager.GetObject("Teleport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Translations {
            get {
                object obj = ResourceManager.GetObject("Translations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Warlock {
            get {
                object obj = ResourceManager.GetObject("Warlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WarlockChainSummon {
            get {
                object obj = ResourceManager.GetObject("WarlockChainSummon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WinterBreath {
            get {
                object obj = ResourceManager.GetObject("WinterBreath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ZenArrow {
            get {
                object obj = ResourceManager.GetObject("ZenArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
