//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolastaCommunityExpansion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolastaCommunityExpansion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AcidClaws {
            get {
                object obj = ResourceManager.GetObject("AcidClaws", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AirBlast {
            get {
                object obj = ResourceManager.GetObject("AirBlast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Bolgrif {
            get {
                object obj = ResourceManager.GetObject("Bolgrif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BurstOfRadiance {
            get {
                object obj = ResourceManager.GetObject("BurstOfRadiance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ContentPack {
            get {
                object obj = ResourceManager.GetObject("ContentPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Darkelf {
            get {
                object obj = ResourceManager.GetObject("Darkelf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DeadeyeConcentrationIcon {
            get {
                object obj = ResourceManager.GetObject("DeadeyeConcentrationIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DeadeyeIcon {
            get {
                object obj = ResourceManager.GetObject("DeadeyeIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EarthTremor {
            get {
                object obj = ResourceManager.GetObject("EarthTremor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchBlast {
            get {
                object obj = ResourceManager.GetObject("EldritchBlast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchBlastGrasp {
            get {
                object obj = ResourceManager.GetObject("EldritchBlastGrasp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchBlastRepell {
            get {
                object obj = ResourceManager.GetObject("EldritchBlastRepell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EldritchInvocation {
            get {
                object obj = ResourceManager.GetObject("EldritchInvocation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalForm {
            get {
                object obj = ResourceManager.GetObject("ElementalForm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalFormEnhanced {
            get {
                object obj = ResourceManager.GetObject("ElementalFormEnhanced", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalFormIcon {
            get {
                object obj = ResourceManager.GetObject("ElementalFormIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ElementalFormIconEnhanced {
            get {
                object obj = ResourceManager.GetObject("ElementalFormIconEnhanced", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Entry {
            get {
                object obj = ResourceManager.GetObject("Entry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fire {
            get {
                object obj = ResourceManager.GetObject("Fire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FlurryOfArrows {
            get {
                object obj = ResourceManager.GetObject("FlurryOfArrows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action/&amp;ActionDisarmDescription	[OBSOLEADO]Haz clic para desarmar esta trampa.
        ///Action/&amp;ActionManipulateDescription	[OBSOLEADO]Haz clic para interactuar con este objeto.
        ///Action/&amp;ActionObserveDescription	[OBSOLETE]Haz clic para examinar este objeto.
        ///Action/&amp;ActionStatusAvailableDescription	Esta acción está disponible para su uso durante el turno de este personaje.
        ///Action/&amp;ActionStatusCannotPerformDescription	Esta criatura no puede realizar este tipo de acción.
        ///Action/&amp;ActionStatusEngagedDescription	Acció [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Game_es {
            get {
                return ResourceManager.GetString("Game-es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action/&amp;ActionDisarmDescription	[OBSOLETE]Fare clic per disattivare questa trappola.
        ///Action/&amp;ActionManipulateDescription	[OBSOLETE]Fare clic per interagire con questo oggetto.
        ///Action/&amp;ActionObserveDescription	[OBSOLETE]Fare clic per esaminare questo oggetto.
        ///Action/&amp;ActionStatusAvailableDescription	Questa azione può essere utilizzata durante il turno di questo personaggio.
        ///Action/&amp;ActionStatusCannotPerformDescription	Questa creatura non può eseguire questo tipo di azione.
        ///Action/&amp;ActionStatusEngagedDes [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Game_it {
            get {
                return ResourceManager.GetString("Game-it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gnome {
            get {
                object obj = ResourceManager.GetObject("Gnome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Halberd {
            get {
                object obj = ResourceManager.GetObject("Halberd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Halberd_1 {
            get {
                object obj = ResourceManager.GetObject("Halberd_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Halberd_2 {
            get {
                object obj = ResourceManager.GetObject("Halberd_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HalberdLightning {
            get {
                object obj = ResourceManager.GetObject("HalberdLightning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HalberdPrimed {
            get {
                object obj = ResourceManager.GetObject("HalberdPrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbow {
            get {
                object obj = ResourceManager.GetObject("HandXbow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbow_1 {
            get {
                object obj = ResourceManager.GetObject("HandXbow_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbow_2 {
            get {
                object obj = ResourceManager.GetObject("HandXbow_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbowAcid {
            get {
                object obj = ResourceManager.GetObject("HandXbowAcid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HandXbowPrimed {
            get {
                object obj = ResourceManager.GetObject("HandXbowPrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HellishRebuke {
            get {
                object obj = ResourceManager.GetObject("HellishRebuke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMace {
            get {
                object obj = ResourceManager.GetObject("LongMace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMace_1 {
            get {
                object obj = ResourceManager.GetObject("LongMace_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMace_2 {
            get {
                object obj = ResourceManager.GetObject("LongMace_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMacePrimed {
            get {
                object obj = ResourceManager.GetObject("LongMacePrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LongMaceThunder {
            get {
                object obj = ResourceManager.GetObject("LongMaceThunder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Alle zum Shop hinzufügen
        ///ModUi/&amp;AddBleedingToLesserRestoration	Fügen Sie den Zustand &lt;color=orange&gt;Bluten&lt;/color&gt; zu den Zuständen hinzu, die durch &lt;color=orange&gt;Größere und Geringere Wiederherstellung&lt;/color&gt; entfernt wurden
        ///ModUi/&amp;AddHelpActionToAllRaces	Füge allen Rennen die Aktion &lt;color=orange&gt;Hilfe&lt;/color&gt; hinzu
        ///ModUi/&amp;AddNewWeaponsAndRecipesToShops	Füge den Läden neue Waffen und Rezepte hinzu &lt;i&gt;&lt;color=yellow&gt;[Handbandagen, Hellebarden, Hechte, lange Keulen, Handarmbrüste]&lt;/co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_de {
            get {
                return ResourceManager.GetString("Modui-de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Add all to store
        ///ModUi/&amp;AddBleedingToLesserRestoration	Add the &lt;color=orange&gt;Bleeding&lt;/color&gt; condition to the conditions removed by &lt;color=orange&gt;Greater and Lesser Restoration&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Add the &lt;color=orange&gt;Help&lt;/color&gt; action to all races
        ///ModUi/&amp;AddNewWeaponsAndRecipesToShops	Add new weapons and recipes to shops &lt;i&gt;&lt;color=yellow&gt;[hand wraps, halberds, pikes, long maces, hand crossbows]&lt;/color&gt;&lt;/i&gt; &lt;b&gt;&lt;i&gt;&lt;color=#C04040E0&gt;[Requires Restart]&lt;/color&gt;&lt;/i&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_en {
            get {
                return ResourceManager.GetString("Modui-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Añadir todo a la tienda
        ///ModUi/&amp;AddBleedingToLesserRestoration	Añade la condición &lt;color=#FFA500&gt;Sangrado&lt;/color&gt; a las condiciones eliminadas por &lt;color=#FFA500&gt;Restauración mayor y menor&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Añadir la acción &lt;color=#FFA500&gt;Ayuda&lt;/color&gt; a todas las razas
        ///ModUi/&amp;AddNewWeaponsAndRecipesToShops	Añade nuevas armas y recetas a las tiendas &lt;i&gt;&lt;color=#FFFF00&gt;[envolturas de mano, alabardas, picas, mazas largas, ballestas de mano]&lt;/color&gt;&lt;/i&gt; &lt;b&gt;&lt;i&gt;&lt;color=# [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_es {
            get {
                return ResourceManager.GetString("Modui-es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Ajouter tout au magasin
        ///ModUi/&amp;AddBleedingToLesserRestoration	Ajoutez la condition &lt;color=orange&gt;Saignement&lt;/color&gt; aux conditions supprimées par &lt;color=orange&gt;Grande et Petite Restauration&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Ajouter l&apos;action &lt;color=orange&gt;Aide&lt;/color&gt; à toutes les courses
        ///ModUi/&amp;AddNewWeaponsAndRecipesToShops	Ajouter de nouvelles armes et recettes aux boutiques &lt;i&gt;&lt;color=yellow&gt;[bandages à main, hallebardes, piques, masses longues, arbalètes à main]&lt;/color&gt;&lt;/i&gt; &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_fr {
            get {
                return ResourceManager.GetString("Modui-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Aggiungi tutti al negozio
        ///ModUi/&amp;AddBleedingToLesserRestoration	Aggiungere la condizione &lt;color=#FFA500&gt;Sanguinamento&lt;/color&gt; alle condizioni rimosse da &lt;color=#FFA500&gt;Restauro maggiore e minore&lt;/color&gt;.
        ///ModUi/&amp;AddHelpActionToAllRaces	Aggiungere l&apos;azione &lt;color=#FFA500&gt;Aiuto&lt;/color&gt; a tutte le razze
        ///ModUi/&amp;AddNewWeaponsAndRecipesToShops	Aggiungere nuove armi e ricette ai negozi &lt;i&gt;&lt;color=#FFFF00&gt;[fasce a mano, alabarde, picche, mazze lunghe, balestre a mano]&lt;/color&gt;&lt;/i&gt; &lt;b&gt;&lt;i&gt;&lt;color= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_it {
            get {
                return ResourceManager.GetString("Modui-it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Adicionar tudo à loja
        ///ModUi/&amp;AddBleedingToLesserRestoration	Adicione a condição &lt;color=orange&gt;Sangramento&lt;/color&gt; às condições removidas pela &lt;color=orange&gt;Restauração Maior e Menor&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Adicione a ação &lt;color=orange&gt;Ajuda&lt;/color&gt; a todas as corridas
        ///ModUi/&amp;AddNewWeaponsAndRecipesToShops	Adicione novas armas e receitas às lojas &lt;i&gt;&lt;color=yellow&gt;[bandeiras de mão, alabardas, lanças, maças longas, bestas de mão]&lt;/color&gt;&lt;/i&gt; &lt;b&gt;&lt;i&gt;&lt;color=#C04040E0&gt;[ Req [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_pt_BR {
            get {
                return ResourceManager.GetString("Modui-pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	Добавить все в магазин
        ///ModUi/&amp;AddBleedingToLesserRestoration	Добавить состояние &lt;color=orange&gt;Кровотечение&lt;/color&gt; к состояниям, снимаемым &lt;color=orange&gt;Большим и Малым восстановлением&lt;/color&gt;
        ///ModUi/&amp;AddHelpActionToAllRaces	Добавить действие &lt;color=orange&gt;Помощь&lt;/color&gt; всем расам.
        ///ModUi/&amp;AddNewWeaponsAndRecipesToEditor	&lt;i&gt;+ Также добаить их в Создатель Подземелий&lt;/i&gt;
        ///ModUi/&amp;AddPickpocketableLoot	Добавить добычу для карманных краж &lt;i&gt;&lt;color=yellow&gt;[рекомендуется, если умение &lt;color= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_ru {
            get {
                return ResourceManager.GetString("Modui-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModUi/&amp;AddAllToStore	全部加入商店
        ///ModUi/&amp;AddBleedingToLesserRestoration	添加&lt;color=orange&gt;流血&lt;/color&gt;状态至&lt;color=orange&gt;次级/高等复原术&lt;/color&gt;的移除效果范围
        ///ModUi/&amp;AddHelpActionToAllRaces	添加&lt;color=orange&gt;协助&lt;/color&gt;至全部种族
        ///ModUi/&amp;AddNewWeaponsAndRecipesToShops	添加新的武器和配方至商店&lt;i&gt;&lt;color=yellow&gt;[裹手，戟，长矛，长钉头锤，手弩]&lt;/color&gt;&lt;/i&gt; &lt;i&gt;&lt;color=#C04040E0&gt;[需要重启游戏]&lt;/color&gt;&lt;/i&gt;
        ///ModUi/&amp;AddPickpocketableLoot	添加可扒窃的战利品 &lt;i&gt;&lt;color=yellow&gt;[建议在&lt;color=orange&gt;扒窃&lt;/color&gt;专长被启用时启用]&lt;/color&gt;&lt;/i&gt;
        ///ModUi/&amp;AddToStore	加入商店
        ///ModUi/&amp;Advanced	&lt;color=yellow&gt;进阶选项：&lt;/color&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Modui_zh_CN {
            get {
                return ResourceManager.GetString("Modui-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Monk {
            get {
                object obj = ResourceManager.GetObject("Monk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkEmptyBody {
            get {
                object obj = ResourceManager.GetObject("MonkEmptyBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkFlurryOfBlows {
            get {
                object obj = ResourceManager.GetObject("MonkFlurryOfBlows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkKiIcon {
            get {
                object obj = ResourceManager.GetObject("MonkKiIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkPatientDefense {
            get {
                object obj = ResourceManager.GetObject("MonkPatientDefense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkPictogram {
            get {
                object obj = ResourceManager.GetObject("MonkPictogram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkSlowFall {
            get {
                object obj = ResourceManager.GetObject("MonkSlowFall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkStepOfTheWind {
            get {
                object obj = ResourceManager.GetObject("MonkStepOfTheWind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkStillnessOfMind {
            get {
                object obj = ResourceManager.GetObject("MonkStillnessOfMind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MonkStunningStrike {
            get {
                object obj = ResourceManager.GetObject("MonkStunningStrike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Umgekehrte Schwerkraft
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Umgekehrte Schwerkraft
        ///Condition/&amp;DH_TimeStop_Spell_Description	Eingefroren durch Zeitstopp
        ///Condition/&amp;DH_TimeStop_Spell_Title	Eingefroren durch Zeitstopp
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Gewitter
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Gewitter
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Beliebiger Feuerball
        ///Feature/&amp;DH_AtWill_Fireball_Power_Titl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_de {
            get {
                return ResourceManager.GetString("Monsters-de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Reverse Gravity
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Reverse Gravity
        ///Condition/&amp;DH_TimeStop_Spell_Description	Frozen by Time Stop
        ///Condition/&amp;DH_TimeStop_Spell_Title	Frozen by Time Stop
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Lightning Storm
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Lightning Storm
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	At-will Fireball
        ///Feature/&amp;DH_AtWill_Fireball_Power_Title	Fireball
        ///Feature/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_en {
            get {
                return ResourceManager.GetString("Monsters-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Gravedad inversa
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Gravedad inversa
        ///Condition/&amp;DH_TimeStop_Spell_Description	Congelado por el Tiempo Parado
        ///Condition/&amp;DH_TimeStop_Spell_Title	Congelado por la parada del tiempo
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Tormenta de rayos
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Tormenta de rayos
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Bola de fuego a voluntad
        ///Feature/&amp;DH_AtWill [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_es {
            get {
                return ResourceManager.GetString("Monsters-es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Gravité inversée
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Gravité inversée
        ///Condition/&amp;DH_TimeStop_Spell_Description	Gelé par l&apos;arrêt du temps
        ///Condition/&amp;DH_TimeStop_Spell_Title	Gelé par l&apos;arrêt du temps
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Orage
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Orage
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Boule de feu à volonté
        ///Feature/&amp;DH_AtWill_Fireball_Power_Title	Boule de feu
        ///Feat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_fr {
            get {
                return ResourceManager.GetString("Monsters-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Gravità inversa
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Gravità inversa
        ///Condition/&amp;DH_TimeStop_Spell_Description	Congelato da Time Stop
        ///Condition/&amp;DH_TimeStop_Spell_Title	Congelato dall&apos;arresto del tempo
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Tempesta di fulmini
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Tempesta di fulmini
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Palla di fuoco a volontà
        ///Feature/&amp;DH_AtWill_Firebal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_it {
            get {
                return ResourceManager.GetString("Monsters-it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Gravidade reversa
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Gravidade reversa
        ///Condition/&amp;DH_TimeStop_Spell_Description	Congelado por Parada de Tempo
        ///Condition/&amp;DH_TimeStop_Spell_Title	Congelado por Parada de Tempo
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Tempestade Relâmpago
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Tempestade Relâmpago
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Bola de fogo à vontade
        ///Feature/&amp;DH_AtWill [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_pt_BR {
            get {
                return ResourceManager.GetString("Monsters-pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	Обратная гравитация
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	Обратная гравитация
        ///Condition/&amp;DH_TimeStop_Spell_Description	Застыло на остановке времени
        ///Condition/&amp;DH_TimeStop_Spell_Title	Застыло на остановке времени
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	Грозовой шторм
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	Грозовой шторм
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	Неограниченный огненный шар
        ///Feature/&amp;DH_AtWill_Fire [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_ru {
            get {
                return ResourceManager.GetString("Monsters-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition/&amp;DH_ReverseGravity_Spell_Description	反重力
        ///Condition/&amp;DH_ReverseGravity_Spell_Title	反重力
        ///Condition/&amp;DH_TimeStop_Spell_Description	因时间停止而冻结
        ///Condition/&amp;DH_TimeStop_Spell_Title	因时间停止而冻结
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Description	闪电风暴
        ///Feature/&amp;DH_AirTitan_LightningStorm_Custom_Power_Title	闪电风暴
        ///Feature/&amp;DH_AtWill_Fireball_Power_Description	任意施放火球术
        ///Feature/&amp;DH_AtWill_Fireball_Power_Title	火球术
        ///Feature/&amp;DH_AtWill_HoldMonster_Power_Description	每天3次
        ///Feature/&amp;DH_AtWill_HoldMonster_Powe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Monsters_zh_CN {
            get {
                return ResourceManager.GetString("Monsters-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DwarfFemale	Abagtha
        ///DwarfFemale	Bera
        ///DwarfFemale	Birsha
        ///DwarfFemale	Brallesyl
        ///DwarfFemale	Bretri
        ///DwarfFemale	Bronnura
        ///DwarfFemale	Clauda
        ///DwarfFemale	Dabareh
        ///DwarfFemale	Dearma
        ///DwarfFemale	Demelza
        ///DwarfFemale	Dodai
        ///DwarfFemale	Dura
        ///DwarfFemale	Gath
        ///DwarfFemale	Hadar
        ///DwarfFemale	Hagar
        ///DwarfFemale	Halah
        ///DwarfFemale	Hanan
        ///DwarfFemale	Iddo
        ///DwarfFemale	Jenndora
        ///DwarfFemale	Jenrin
        ///DwarfFemale	Juttah
        ///DwarfFemale	Melea
        ///DwarfFemale	Meribah
        ///DwarfFemale	Misnan
        ///DwarfFemale	Myrnera
        ///DwarfFemale	Na [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Names_en {
            get {
                return ResourceManager.GetString("Names-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Pike {
            get {
                object obj = ResourceManager.GetObject("Pike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Pike_1 {
            get {
                object obj = ResourceManager.GetObject("Pike_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Pike_2 {
            get {
                object obj = ResourceManager.GetObject("Pike_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PikePrimed {
            get {
                object obj = ResourceManager.GetObject("PikePrimed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PikePsychic {
            get {
                object obj = ResourceManager.GetObject("PikePsychic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PowerAttackConcentrationIcon {
            get {
                object obj = ResourceManager.GetObject("PowerAttackConcentrationIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PowerAttackIcon {
            get {
                object obj = ResourceManager.GetObject("PowerAttackIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ResonatingStrike {
            get {
                object obj = ResourceManager.GetObject("ResonatingStrike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SunlightBlade {
            get {
                object obj = ResourceManager.GetObject("SunlightBlade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Teleport {
            get {
                object obj = ResourceManager.GetObject("Teleport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Kann keine Zauber wirken.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC ist auf 16 eingestellt.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Rindenleder
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Charismawert ist gleich 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Schwaches Charisma
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Intelligenzwert ist gleich 1.
        ///AttributeModifier/&amp;DHFeeblemindIntSpellTi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_de {
            get {
                return ResourceManager.GetString("Translations-de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Unable to cast spells.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC is set to 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Barkskin
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Charisma score equals 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Feeble Charisma
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Intelligence score equals 1.
        ///AttributeModifier/&amp;DHFeeblemindIntSpellTitle	Feeble Intelligenc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_en {
            get {
                return ResourceManager.GetString("Translations-en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	No puede lanzar hechizos.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	La CA es de 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Piel de corteza
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	La puntuación de carisma es igual a 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Carisma débil
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	La puntuación de Inteligencia es igual a 1.
        ///AttributeModifier/&amp;DHFeeble [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_es {
            get {
                return ResourceManager.GetString("Translations-es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Impossible de lancer des sorts.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	CA est réglé sur 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Écorce
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Le score de Charisme est égal à 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Charisme faible
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Le score d&apos;intelligence est égal à 1.
        ///AttributeModifier/&amp;DHFeeblemindIn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_fr {
            get {
                return ResourceManager.GetString("Translations-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Impossibile lanciare incantesimi.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	La CA è impostata a 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Pelle di corteccia
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Il punteggio di Carisma è uguale a 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Carisma debole
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Il punteggio di Intelligenza è pari a 1.
        ///AttributeMo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_it {
            get {
                return ResourceManager.GetString("Translations-it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Incapaz de lançar feitiços.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC está definido para 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Barkskin
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	A pontuação de Carisma é igual a 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Carisma fraco
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	A pontuação de inteligência é igual a 1.
        ///AttributeModifier/&amp;DHFeeblem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_pt_BR {
            get {
                return ResourceManager.GetString("Translations-pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	Невозможно читать заклинания.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC настроен на 16.
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	Дубовая кожа
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	Показатель харизмы равен 1.
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	Слабая харизма
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	Показатель интеллекта равен 1.
        ///AttributeModifier/&amp;DHFeeblemindIntSpellTitle	С [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_ru {
            get {
                return ResourceManager.GetString("Translations-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffinity/&amp;DHFeeblemindSpellDescription	无法施法
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinDescription	AC设为16
        ///AttributeModifier/&amp;AncientForestAttributeModifierBarkskinTitle	树肤术
        ///AttributeModifier/&amp;DHFeeblemindChaSpellDescription	魅力值为1
        ///AttributeModifier/&amp;DHFeeblemindChaSpellTitle	魅力衰减
        ///AttributeModifier/&amp;DHFeeblemindIntSpellDescription	智力值为1
        ///AttributeModifier/&amp;DHFeeblemindIntSpellTitle	智力衰减
        ///BlueprintCategory/&amp;FlatRoomsTitle	平房
        ///Caption/&amp;GadgetParametersCustomRemoveDescription	移除:\n{0}
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations_zh_CN {
            get {
                return ResourceManager.GetString("Translations-zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Warlock {
            get {
                object obj = ResourceManager.GetObject("Warlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WarlockChainSummon {
            get {
                object obj = ResourceManager.GetObject("WarlockChainSummon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WinterBreath {
            get {
                object obj = ResourceManager.GetObject("WinterBreath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ZenArrow {
            get {
                object obj = ResourceManager.GetObject("ZenArrow", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
