// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "namespace", Target = "~N:SolastaCommunityExpansion")]
[assembly: SuppressMessage("Roslynator", "RCS1093:Remove file with no code.", Justification = "keeping code for reference")]
[assembly: SuppressMessage("Roslynator", "ROS0003")]

// namespaces
[assembly: SuppressMessage("", "IDE0130", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "IDE0130", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:SolastaModApi")]

// modkit
[assembly: SuppressMessage("", "S101", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S108", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S112", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S125", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S927", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1066", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1104", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1117", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1121", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1123", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1155", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1481", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1643", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1854", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1905", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S1939", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2190", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2201", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2223", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2292", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2328", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2386", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2486", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2695", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2696", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2930", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2971", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2997", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3011", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3218", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3260", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3267", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3358", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3442", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3881", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S3925", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S4136", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S4487", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1041", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1069", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1806", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1816", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1822", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1825", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1827", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA1829", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "CA2211", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "S2223", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "IDE0060", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "IDE0059", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "IDE0063", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "IDE1006", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Leaving for backward compatibility", Scope = "member", Target = "~T:SolastaModApi.DatabaseHelper.CreditsGroupDefinitions")]

[assembly: SuppressMessage("Roslynator", "ROS0003")]

[assembly: SuppressMessage("", "RCS1001", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1003", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1021", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1036", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1037", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1041", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1071", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1077", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1079", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1085", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1089", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1118", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1123", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1146", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1160", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1154", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1163", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1169", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1171", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1179", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1180", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1189", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1196", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1199", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1202", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1212", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1224", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1226", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1234", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]
[assembly: SuppressMessage("", "RCS1238", Justification = "3rd party source", Scope = "namespaceanddescendants", Target = "~N:ModKit")]

[assembly: SuppressMessage("Roslynator", "RCS1112:Combine 'Enumerable.Where' method chain.", Justification = "<Pending>", Scope = "namespaceanddescendants", Target = "~N:SolastaModApi")]
[assembly: SuppressMessage("Major Code Smell", "S3011:Reflection should not be used to increase accessibility of classes, methods, or fields",
    Justification = "Reflection is required", Scope = "namespaceanddescendants", Target = "~N:SolastaCommunityExpansion")]
